stages:
  - init
  - plan
  - apply

variables:
  TF_ROOT: "terraform"

before_script:
  - apt-get update && apt-get install -y unzip
  - rm -rf terraform/
  - curl -sSLO "https://releases.hashicorp.com/terraform/1.10.5/terraform_1.10.5_linux_amd64.zip"
  - unzip -oq terraform_1.10.5_linux_amd64.zip 
  - mv terraform /usr/local/bin/
  - chmod +x /usr/local/bin/terraform
  - terraform --version

init:
  stage: init
  script:
    # - cd $TF_ROOT
    - terraform init
  artifacts:
    paths:
      - .terraform/   # Persist Terraform working directory
      - terraform.tfstate  # Save Terraform state
      - *.tf   # Include Terraform configuration files
    expire_in: 1h

plan:
  stage: plan
  script:
    - terraform plan
  dependencies:
    - init  # Ensures the `plan` stage depends on `init`
  only:
    - merge_requests
    - branches

apply:
  stage: apply
  script:
    - terraform apply -auto-approve
  dependencies:
    - plan  # Ensures `apply` gets files from `plan`
  only:
    - main
  when: manual
