stages:
  - init
  - plan
  - apply

variables:
  TF_ROOT: "terraform"

before_script:
  - apt-get update && apt-get install -y unzip curl jq
  - rm -rf terraform/
  - curl -sSLO "https://releases.hashicorp.com/terraform/1.10.5/terraform_1.10.5_linux_amd64.zip"
  - unzip -oq terraform_1.10.5_linux_amd64.zip 
  - mv terraform /usr/local/bin/
  - chmod +x /usr/local/bin/terraform
  - terraform --version
  - git reset --hard  # Ensure repo files are restored
  - git config --global --add safe.directory /builds/$CI_PROJECT_PATH
  - ls -la  # Debugging: Check if terraform/ exists
  - ls -R terraform  # Debugging: List all files inside terraform
  - chmod +x scripts/vault_aws_env.sh


# init:
#   stage: init
#   script:
#     - ls -la
#     - cd $TF_ROOT
#     - terraform init
#   artifacts:
#     paths:
#       - terraform/.terraform/**  # Store Terraform working directory
#       - terraform/.terraform.lock.hcl
#       - terraform/terraform.tfstate
#       - terraform/terraform.tfstate.backup
#       - "terraform/*.tf"
#       - "terraform/*.tfvars"

plan:
  stage: plan
  # dependencies:
  #   - init  # Ensures the `plan` stage depends on `init`
  script:
    - cd $TF_ROOT
    - ls -la
    - terraform init
    - ../scripts/vault_aws_env.sh terraform plan
  artifacts:
    paths:
      - terraform/terraform.tfstate
      - terraform/terraform.tfstate.backup

apply:
  stage: apply
  # dependencies:
  #   - init
  #   - plan  # Ensures `apply` gets files from `plan`
  script:
    - cd $TF_ROOT
    - ls -la
    - terraform init -reconfigure
    - terraform apply -auto-approve
  only:
    - main
  when: manual