stages:
  - init
  - plan
  - apply

variables:
  TF_ROOT: "terraform"

before_script:
  - apt-get update && apt-get install -y unzip
  - rm -rf terraform/
  - curl -sSLO "https://releases.hashicorp.com/terraform/1.10.5/terraform_1.10.5_linux_amd64.zip"
  - unzip -oq terraform_1.10.5_linux_amd64.zip 
  - mv terraform /usr/local/bin/
  - chmod +x /usr/local/bin/terraform
  - terraform --version
  - git reset --hard  # Ensure repo files are restored
  - git config --global --add safe.directory /builds/$CI_PROJECT_PATH
  - ls -la  # Debugging: Check if terraform/ exists
  - ls -R terraform  # Debugging: List all files inside terraform/

    #Fetch vault
    # Login to Vault using AppRole
  - VAULT_TOKEN=$(curl --silent --request POST \
    --data "{\"role_id\":\"$VAULT_ROLE_ID\", \"secret_id\":\"$VAULT_SECRET_ID\"}" \
    "$VAULT_ADDR/v1/auth/approle/login" | jq -r '.auth.client_token')

  # Fetch secrets from Vault KV v2 at path gitlab/ci-app
  - VAULT_RESPONSE=$(curl --silent \
    --header "X-Vault-Token: $VAULT_TOKEN" \
    "$VAULT_ADDR/v1/gitlab/data/ci-app")

  # Parse and export secrets
  - export AWS_ACCESS_KEY_ID=$(echo "$VAULT_RESPONSE" | jq -r '.data.data.AWS_ACCESS_KEY_ID')
  - export AWS_SECRET_ACCESS_KEY=$(echo "$VAULT_RESPONSE" | jq -r '.data.data.AWS_SECRET_ACCESS_KEY')


init:
  stage: init
  script:
    - ls -la
    - cd $TF_ROOT
    - terraform init
  artifacts:
    paths:
      - terraform/.terraform/**  # Store Terraform working directory
      - terraform/.terraform.lock.hcl
      - terraform/terraform.tfstate
      - terraform/terraform.tfstate.backup
      - "terraform/*.tf"
      - "terraform/*.tfvars"

plan:
  stage: plan
  dependencies:
    - init  # Ensures the `plan` stage depends on `init`
  script:
    - cd $TF_ROOT
    - ls -la
    - terraform init -reconfigure
    - terraform plan
  artifacts:
    paths:
      - terraform/terraform.tfstate
      - terraform/terraform.tfstate.backup

apply:
  stage: apply
  dependencies:
    - init
    - plan  # Ensures `apply` gets files from `plan`
  script:
    - cd $TF_ROOT
    - ls -la
    - terraform init -reconfigure
    - terraform apply -auto-approve
  only:
    - main
  when: manual